title: the Daily Experience
logo: "" # You can add own logo image.
description: 
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Bhaskar Kishor
  bio: Hi, my name is Bhaskar Kishor. I like learning about new techy things that are happening everydag in different corners of the world. Visiting different places and different experience are my things. 

# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/bhasker.kishor # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/bhaskerkishor # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle
email: bhaskarkishor23@gmail.com # Add your Email address
linkedin: https://linkedin.com/in/bhaskar-kishor

# Hero Section
hero: true # To enable the section hero, use the value true. To turn off use the value false.
hero-title: the Daily Experience # Add your hero title
hero-subtitle:  # Add your hero subtitle
hero-image: images/14.jpg # Add background image in section hero

# Footer
footer-image: images/14.jpg # Add background image in footer

# Comment Section (Disqus)
disqus-identifier: daily-experience # Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: "" # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
